language: python
services: mongodb
python:
  - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
  - cd application/
  - pytest --cov=./
  - cd ..
after_success:
    - coveralls
